import React from "react";
import Layout from "../components/layout";
import HeaderTwo from "../components/header/header-two";
import StickyHeader from "../components/header/sticky-header";
import PageHeader from "../components/page-header";
import BrandCarousel from "../components/brand-carousel";
import { Container, Row, Col } from "react-bootstrap";
import Footer from "../components/footer";
import Head from "next/head";

const Forsaljningsvillkor = () => {
  return (
    <>
      <Head>
        <title>Nutzungsbedingungen</title>
        <meta name="title" content="Nutzungsbedingungen - GreenPlank.se" />
        <meta name="description" content="Läs det här dokumentet noggrant. Den innehåller viktig information om dina rättigheter och skyldigheter samt begränsningar och uteslutningar som gäller dig." />
      </Head>
      <Layout pageTitle="Nutzungsbedingungen">
        <HeaderTwo />
        <PageHeader title="Nutzungsbedingungen" crumbTitle="Nutzungsbedingungen" />
        <StickyHeader />
        <section className="about-one pt-120 pb-40">
          <Container>
            <Row style={{ marginBottom: "4em" }}>
              <Col lg={12}>
                <h2>Nutzungsbedingungen</h2>
                <div className="mb-30">
                  <p>Willkommen auf der Green Plank-Website (die „Site“). VOR DER NUTZUNG DER WEBSITE MÜSSEN SIE DIE FOLGENDEN NUTZUNGSBEDINGUNGEN, DIE DARAUF BEZOGENEN RICHTLINIEN UND BEDINGUNGEN SOWIE DIE FOLGENDEN ÄNDERUNGEN DES VORANGEGANGENEN LESEN, VERSTEHEN UND EINVERSTANDEN SEIN. Durch die Nutzung dieser Website erklären Sie sich mit diesen Nutzungsbedingungen einverstanden. Wenn Sie mit einem Teil dieser Nutzungsbedingungen nicht einverstanden sind, NUTZEN SIE DIESE WEBSITE NICHT UND LADEN SIE KEINE MATERIALIEN HERUNTER.</p>
                  <p className="mb-30 mt-30">Green Plank AB („Green Plank“) behält sich das Recht vor, die Bestimmungen und Bedingungen in den Nutzungsbedingungen oder Richtlinien oder Richtlinien der Website jederzeit und nach eigenem Ermessen zu ändern. Jegliche Änderungen oder Modifikationen werden wirksam, sobald die Änderungen auf der Website veröffentlicht und bekannt gegeben werden. Durch Ihre fortgesetzte Nutzung dieser Website nach der Veröffentlichung ihrer Änderungen oder Modifikationen erklären Sie sich mit solchen Änderungen oder Modifikationen einverstanden. Daher sollten Sie die Nutzungsbedingungen und die geltenden Richtlinien von Zeit zu Zeit überprüfen, um die für Ihre Nutzung der Website geltenden Nutzungsbedingungen zu verstehen.</p>
                  <p className="mb-30 mt-30">Diese Nutzungsbedingungen ändern in keiner Weise die Bestimmungen oder Bedingungen einer anderen Vereinbarung, die Sie möglicherweise mit Green Plank für andere Produkte oder Dienstleistungen geschlossen haben.</p>
                  <p className="mb-30 mt-30">Fragen oder Kommentare zu der Site oder ihren Inhalten richten Sie bitte an</p>
                  <h3 className="mb-30 mt-30"><strong>1. </strong>Datenschutz-Bestimmungen</h3>
                  <p className="mb-30 mt-30">Green Plank ist fest davon überzeugt, die Privatsphäre der Nutzer zu schützen und Sie über die Erhebung und Nutzung von Daten durch Green Plank zu informieren, einschließlich personenbezogener Daten, die auf der Website gesammelt wurden. Deshalb hat Green Plank a Datenschutz-Bestimmungen dass Sie sich darauf beziehen sollten, vollständig zu verstehen, wie Green Plank Informationen verwendet und sammelt.</p>
                  <h3 className="mb-30 mt-30"><strong>2. </strong>Verkaufsbedingungen</h3>
                  <p className="mb-30 mt-30">Alle Bestellungen, die über die Website eingehen, unterliegen den Verkaufsbedingungen von Green Plank. Sie sollten sich auf unsere beziehen Verkaufsbedingungen Erfahren Sie mehr über geltende Produktgarantien, unsere Rückgabebedingungen und Versandbedingungen. Durch die Bestellung und / oder Annahme der Lieferung der Produkte erklären Sie sich damit einverstanden, an diese gebunden zu sein Verkaufsbedingungen, Rückgabebedingungen, Versandbedingungen einschließlich der darin enthaltenen Haftungsausschlüsse und Haftungsbeschränkungen. Die Verkaufsbedingungen, die Rückgaberichtlinien und die Versandbedingungen können jederzeit nach Ermessen von Green Plank ohne vorherige Ankündigung geändert werden. Sie sollten daher die Verkaufsbedingungen, die Rückgaberichtlinien und die Versandbedingungen bei jedem Kauf überprüfen.</p>
                  <h3 className="mb-30 mt-30"><strong>3. </strong>Nutzungsbedingungen der Website (Nutzungsvereinbarung)</h3>
                  <ul>
                    <li className="mb-30 mt-10">Durch Herunterladen, Kopieren, Reproduzieren, Weiterverbreiten, Drucken oder Verwenden von Material, das Eigentum von Green Plank AB (Green Plank) ist und speziell auf der Green Plank-Website zur Verfügung gestellt wird, erklären Sie sich mit dieser Nutzungsbedingungen einverstanden Nutzungsbedingungen.</li>
                    <li className="mb-30 mt-10">Unter Material versteht man Werke in schriftlicher, grafischer, fotografischer, visueller und akustischer Form sowie alle Inhalte von Green Plank, die auf der GreenPlank.eu-Website erscheinen oder implementiert wurden.</li>
                    <li className="mb-30 mt-10">Wie jedes Material auf der GreenPlank.eu-Website ist auch dieses urheberrechtlich geschützt.</li>
                    <li className="mb-30 mt-10">Die Erlaubnis (Erlaubnis) zur Nutzung des Website-Materials von Green Plank wird unter den in diesen Nutzungsbedingungen festgelegten Bedingungen erteilt.</li>
                    <li className="mb-30 mt-10">Nichts in der Erteilung dieser Erlaubnis begründet ein unwiderrufliches Privileg oder Recht des Nutzers.</li>
                    <li className="mb-30 mt-10">Green Plank behält sich das Recht vor, die Erlaubnis zur Nutzung seiner urheberrechtlich geschützten Materialien zu widerrufen, falls Green Plank feststellt, dass der Nutzer des urheberrechtlich geschützten Materials das Recht missbraucht hat, das Material auf die in diesen Nutzungsbedingungen festgelegte Weise zu nutzen.</li>
                    <li className="mb-30 mt-10">Der Benutzer des urheberrechtlich geschützten Materials hat nach Benachrichtigung von Green Plank die Nutzung des Materials unverzüglich einzustellen und zu unterlassen. Wenn das Material auf einer Website angezeigt wird, muss das Material unverzüglich von der Website entfernt werden.</li>
                  </ul>
                  <h3 className="mb-30 mt-30"><strong>4. </strong>MITGLIEDSCHAFTSKONTO-PFLICHTEN</h3>
                  <p className="mb-30 mt-10">Nachdem Sie diese Nutzungsbedingungen akzeptiert haben, können Sie ein Mitgliedskonto im Bereich Mitgliedschaft der Website (das „Mitgliedskonto“) als Privatkunde oder Großhändler / Einzelhändler eröffnen. Im Rahmen der Mitgliedschaftsregistrierung kann die Person, die das Mitgliedskonto auf der Website eröffnet (der „Administrator“), uns die Informationen anderer Benutzer übermitteln, die berechtigt sind, bestimmte Funktionen im Namen des Administrators über das Mitgliedskonto auszuführen ( “Autorisierte Benutzer”). Der Administrator muss speziell auswählen, welche Funktionen jeder berechtigte Benutzer über die Site ausführen darf.Autorisierte Benutzer können mit ihren eigenen persönlichen Passwörtern auf die Site zugreifen, die ausgewählten Funktionen jedoch nur im Auftrag des Administrators ausführen. Ein Administrator kann jederzeit das persönliche Kennwort eines berechtigten Benutzers ändern, um seinen Zugriff auf die Site zu verhindern, die Berechtigung des berechtigten Benutzers zur Ausführung bestimmter Funktionen im Namen des Mitglieds einzuschränken oder auf andere Weise berechtigte Benutzer zu ändern, hinzuzufügen oder zu löschen. Wenn ein autorisierter Benutzer nicht mehr berechtigt ist, in Ihrem Namen zu handeln, ist der Administrator dafür verantwortlich, diese Sicherheitsverfahren zu verwenden, die wir Ihnen zur Verfügung gestellt haben, um den Zugriff des autorisierten Benutzers auf die Site zu kündigen oder einzuschränken.</p>
                  <p className="mb-30 mt-10">Sie erhalten ein Kennwort und eine Kontonummer, wenn Sie die Informationen zum Mitgliedskonto eingegeben haben. Wenn Sie der Administrator Ihres Mitgliedskontos sind, stimmen Sie in Anbetracht Ihrer Nutzung der Website zu:</p>
                  <ul>
                    <li>um wahre, genaue, aktuelle und vollständige Informationen über sich selbst und / oder das von Ihnen vertretene Unternehmen bereitzustellen, einschließlich, aber nicht beschränkt auf Informationen über alle autorisierten Benutzer; einschließlich besonderer Umstände oder Einschränkungen, die für jeden berechtigten Benutzer gelten.</li>
                    <li>Sie versichern und garantieren, dass Sie die Fähigkeit und Befugnis besitzen, Vereinbarungen zu treffen und Aufträge für Green Plank-Produkte und -Dienstleistungen für Sie oder Ihr Unternehmen zu erteilen.</li>
                    <li>dass eine Bestellung, die Sie oder ein autorisierter Benutzer über die Website aufgegeben haben, einer unterzeichneten Bestellung entspricht, und Sie hiermit auf jede künftige Anfechtung der Gültigkeit und Durchsetzbarkeit einer Bestellung verzichten, die über die Website auf Grund der elektronischen Übermittlung und Übermittlung übermittelt wurde autorisiert.</li>
                    <li>dass Sie für alle Kosten und Gebühren verantwortlich sind, einschließlich, jedoch nicht beschränkt auf, Telefongebühren und Telekommunikationsausrüstung, die anfallen, um die Site zu nutzen.</li>
                    <li>Sie (und Ihr Unternehmen, falls zutreffend) sind voll verantwortlich für alle Aktivitäten, die unter Ihrem Passwort oder Mitgliedskonto stattfinden, und übernehmen jegliche Haftung für Handlungen oder Unterlassungen Ihrer autorisierten Benutzer, die sich aus deren Nutzung der Website ergeben, selbst wenn dies zutrifft Handlungen oder Unterlassungen werden von Ihnen nicht ausdrücklich genehmigt.</li>
                    <li>uns umgehend über eine unbefugte Verwendung Ihres Passworts oder Ihres Mitgliedskontos oder eine andere Sicherheitsverletzung zu benachrichtigen; und</li>
                    <li>dass Sie vollständig für die Verwaltung Ihres Mitgliedskontos verantwortlich sind, einschließlich, aber nicht beschränkt auf:
                    <p className="mb-30 mt-30"><strong>1. </strong>Wahrung der Vertraulichkeit von Passwörtern und / oder Mitgliedskontoinformationen;</p>
                    <p className="mb-30 mt-30"><strong>2. </strong>Pflege und unverzügliche Aktualisierung der Informationen zum Mitgliedskonto, um sicherzustellen, dass diese wahr, genau, aktuell und vollständig sind;</p>
                    <p className="mb-30 mt-30"><strong>3. </strong>sicherstellen, dass jeder autorisierte Benutzer die Kapazität und Befugnis besitzt, die Funktionen auszuführen, für die er von Ihnen oder Ihrem Unternehmen autorisiert wurde; und</p>
                    <p className="mb-30 mt-30"><strong>4. </strong>Beenden oder Einschränken des Zugriffs eines autorisierten Benutzers auf die Site, wenn ein autorisierter Benutzer nicht mehr berechtigt ist, bestimmte Funktionen in Ihrem Namen auszuführen.</p>
                    </li>
                    <p className="mb-30 mt-30">Wenn Sie unwahre, ungenaue, nicht aktuelle oder unvollständige Informationen übermitteln oder wenn wir den begründeten Verdacht haben, dass diese Informationen nicht wahr, ungenau, nicht aktuell oder unvollständig sind, können wir Ihr Mitgliedskonto sperren oder kündigen und alle aktuellen ablehnen und zukünftige Nutzung der Website durch Sie. Informationen zum Mitgliedskonto und bestimmte andere Informationen über Sie unterliegen unseren Datenschutzbestimmungen. Weitere Informationen finden Sie in unseren Datenschutzbestimmungen.</p>
                  </ul>
                  <h3 className="mb-30 mt-30"><strong>5. </strong>EIGENTUM DES INHALTS</h3>
                  <p className="mb-30 mt-10">Alle auf dieser Website enthaltenen Inhalte sind Eigentum von Green Plank und / oder seinen verschiedenen Drittanbietern und Vertriebshändlern und unterliegen den Gesetzen zum Schutz des geistigen Eigentums von Schweden und anderen Ländern. Keiner der auf dieser Website gefundenen Inhalte darf ohne die ausdrückliche schriftliche Genehmigung von Green Plank und / oder seinen Drittanbietern und Vertriebshändlern reproduziert, erneut veröffentlicht, verteilt, angezeigt, verkauft, übertragen oder geändert werden.</p>
                  <h3 className="mb-30 mt-30"><strong>6. </strong>URHEBERRECHTE</h3>
                  <p className="mb-30 mt-10">Alle urheberrechtlich geschützten und urheberrechtlich geschützten Materialien auf dieser Website, einschließlich, jedoch nicht beschränkt auf das Green Plank-Logo, das Design, die Texte, Grafiken, Bilder und andere Dateien sowie deren Auswahl und Anordnung („Materialien“), sind Eigentum von Green Plank, ALL VORBEHALTENE RECHTE Copyright © 2010 Green Plank AB und / oder seine Lizenzgeber. Außer wie hierin angegeben, darf keines der Materialien in irgendeiner Form oder auf irgendeine Weise kopiert, reproduziert, verteilt, erneut veröffentlicht, heruntergeladen, angezeigt, veröffentlicht oder übertragen werden, einschließlich, aber nicht beschränkt auf, elektronisch, mechanisch, fotokopiert, aufgezeichnet oder Andernfalls ohne vorherige schriftliche Genehmigung von Green Plank oder des jeweiligen Rechteinhabers.</p>
                  <h3 className="mb-30 mt-30"><strong>7. </strong>MARKEN UND DIENSTLEISTUNGSMARKEN</h3>
                  <p className="mb-30 mt-10">Green Plank, das Green Plank-Logo und die auf dieser Website beschriebenen Produkte und Dienstleistungen, einschließlich, aber nicht beschränkt auf “Green Plank”, sind Marken, Dienstleistungsmarken oder eingetragene Marken von Green Plank und seinen Lieferanten und Lizenzgebern und dürfen nicht kopiert werden ganz oder teilweise ohne vorherige schriftliche Genehmigung von Green Plank oder seinen Zulieferern oder Lizenzgebern nachgeahmt oder verwendet werden. Darüber hinaus sind alle Seitenköpfe, benutzerdefinierten Grafiken, Schaltflächensymbole und Skripte Dienstleistungsmarken, Marken und / oder Markenzeichen von Green Plank und dürfen ohne vorherige Ankündigung weder ganz noch teilweise kopiert, imitiert oder verwendet werden schriftliche Genehmigung von Green Plank. Alle anderen hier erwähnten Marken, eingetragenen Marken, Produktnamen und Green Plank-Namen oder -Logos sind Eigentum ihrer jeweiligen Inhaber.</p>
                  <h3 className="mb-30 mt-30"><strong>8. </strong>NUTZUNG DER WEBSITE</h3>
                  <p className="mb-30 mt-10">Green Plank gewährt Ihnen eine eingeschränkte Lizenz zur Nutzung dieser Website, für rechtmäßige Bestellungen und Einkäufe und darf diese Website nicht für andere Zwecke, einschließlich, ohne Einschränkung, für spekulative, falsche oder betrügerische Bestellungen oder Bestellungen im Vorgriff auf die Nachfrage, verwenden. Diese Gewährung umfasst nicht ohne Einschränkung: (a) den Weiterverkauf oder die kommerzielle Nutzung der Website und / oder der darin enthaltenen Technologie oder Inhalte; (b) das Sammeln und Verwenden von Produktlisten oder -beschreibungen; (c) Nutzung der Website und ihrer Inhalte in abgeleiteten Formaten; oder (d) Verwendung von Data Mining, Robotern oder ähnlichen Datenerfassungs- und -extraktionsmethoden. Mit Ausnahme der oben genannten Ausnahmen erhalten Sie keine Rechte oder Lizenzen, die implizit, in irgendeiner Form oder auf sonstige Weise an Patenten, Marken, Urheberrechten oder Eigentumsrechten von Green Plank oder Dritten beteiligt sind.Diese Site und der auf dieser Site bereitgestellte Inhalt dürfen ohne die schriftliche Genehmigung von Green Plank nicht kopiert, reproduziert, erneut veröffentlicht, hochgeladen, veröffentlicht, übertragen oder verbreitet werden, es sei denn, Sie dürfen die auf dieser Site präsentierten Materialien für das Internet herunterladen, anzeigen und drucken nur für lizenzierte Zwecke; vorausgesetzt, dass Sie nicht ohne die Erlaubnis von Green Plank oder des jeweiligen Inhabers des Urheberrechts (a) Materialien auf einer Website, einem Computernetzwerk oder in Rundfunk- oder Publikationsmedien kopieren, veröffentlichen oder veröffentlichen dürfen, (b) die Materialien modifizieren, und (c) in den Materialien enthaltene Urheberrechts-, Marken- und andere Eigentumsvermerke entfernen oder ändern. Die unbefugte Nutzung dieser Website und / oder der auf dieser Website enthaltenen Materialien kann gegen geltendes Urheberrecht, Markenrecht, andere Gesetze zum Schutz geistigen Eigentums oder andere Gesetze verstoßen.Sie dürfen keine Frametechniken verwenden, um Green Plank-Marken, -Logos oder andere geschützte Informationen (einschließlich der auf dieser Site gefundenen Bilder, des Inhalts von Texten oder des Layouts / Designs einer Seite oder eines Formulars auf einer Seite) einzuschließen ) ohne ausdrückliche schriftliche Zustimmung von Green Plank. Darüber hinaus dürfen Sie ohne die ausdrückliche schriftliche Zustimmung von Green Plank keine Meta-Tags oder sonstigen „versteckten Texte“ verwenden, die einen Green Plank-Namen, eine Marke oder einen Produktnamen verwenden.</p>
                  <h3 className="mb-30 mt-30"><strong>9. </strong>ALTER UND VERANTWORTUNG</h3>
                  <p className="mb-30 mt-10">Sie erklären, dass Sie volljährig sind, um diese Website zu nutzen und verbindliche rechtliche Verpflichtungen für jegliche Haftung zu begründen, die Ihnen durch die Nutzung dieser Website entstehen kann. Ihnen ist bekannt, dass Sie finanziell für alle Nutzungen dieser Website durch Sie und diejenigen, die Ihre Anmeldeinformationen verwenden, verantwortlich sind.</p>
                 
                  <h3 className="mb-30 mt-30"><strong>10. </strong>BEENDIGUNG</h3>
                  <p className="mb-30 mt-10">Sie erklären sich damit einverstanden, dass Green Plank nach eigenem Ermessen Ihr oder eines der Kennwörter, das Konto oder die Nutzung der Website durch einen autorisierten Benutzer kündigen oder den Zugriff Ihres oder eines autorisierten Benutzers auf eine Komponente dieser Website aus irgendeinem Grund einschränken kann, einschließlich ohne Einschränkung. bei Nichtbenutzung oder wenn Green Plank der Ansicht ist, dass Sie oder ein autorisierter Benutzer gegen die Nutzungsbedingungen oder geltende Gesetze oder Bestimmungen verstoßen oder diese verletzt haben. Green Plank kann auch nach eigenem Ermessen und jederzeit die Bereitstellung der Website oder eines Teils davon mit oder ohne Vorankündigung einstellen. Sie erklären sich damit einverstanden, dass eine Beendigung des Zugriffs auf die Website gemäß einer Bestimmung der Nutzungsbedingungen ohne vorherige Ankündigung erfolgen kann, und bestätigen und stimmen zu, dass Green Plank Ihr Mitgliedskonto und alle zugehörigen Informationen und Dateien in Ihrem Konto und / oder Ihrem Konto sofort deaktivieren oder löschen kann. oder einen weiteren Zugriff auf solche Dateien oder die Site sperren. Darüber hinaus erklären Sie sich damit einverstanden, dass Green Plank weder Ihnen noch Dritten gegenüber für die Beendigung oder Einschränkung des Zugriffs auf die Website haftet.</p>
                  <h3 className="mb-30 mt-30"><strong>11. </strong>HAFTUNGSAUSSCHLUSS UND ZUSICHERUNGEN</h3>
                  <p className="mb-30 mt-10">IHRE NUTZUNG DER WEBSITE ERFOLGT AUF EIGENES RISIKO. DIE WEBSITE UND DIE MATERIALIEN SIND “WIE BESEHEN” UND “WIE VERFÜGBAR” ZUR VERFÜGUNG GESTELLT. SIE ERKENNEN AN, DASS SIE VON GREEN PLANK EMPFOHLEN WURDEN, IHRE EIGENE DILIGENZ IN BEZUG AUF DIESE WEBSITE ZU ÜBERNEHMEN. GREEN PLANK ÜBERNIMMT KEINE AUSDRÜCKLICHEN ODER STILLSCHWEIGENDEN ZUSICHERUNGEN ODER GEWÄHRLEISTUNGEN IN BEZUG AUF DIE GREEN PLANK-WEBSITE, IHRE FUNKTION, IHR INHALT, INFORMATIONEN, MATERIALIEN.GREEN PLANKE AUSDRÜCKLICH ALLE ZUSICHERUNGEN UND GARANTIEN, AUSDRÜCKLICH ODER IMPLIZIT, IRGENDEINER ART IN BEZUG AUF DIESER WEBSITE ODER IHRER VERWENDUNG, EINSCHLIESSLICH, ABER NICHT MARKTGÄNGIGKEIT, EIGNUNG FÜR EINEN BESTIMMTEN ZWECK, GENAUIGKEIT, Vollständigkeit, Aktualität, Zuverlässigkeit oder Eignung jedes DER INHALT ODER DIE DATEN, DIE AUF DIESER WEBSITE, IM TITEL UND OHNE VERLETZUNG GEFUNDEN SIND, UND DIE DURCH STATUT ODER ANDERWEITIGES GESETZ ODER EIGENKAPITAL ODER DURCH HANDELSVERHANDLUNG ENTSTEHEN.</p>
                  <h3 className="mb-30 mt-30"><strong>12. </strong>HAFTUNGSBESCHRÄNKUNG</h3>
                  <p className="mb-30 mt-10">SIE STIMMEN ZU, DASS GREEN PLANK, SEINE DIREKTOREN, BEAMTEN, MITARBEITER ODER ANDERE VERTRETER FÜR SCHÄDEN, DIE AUS DEM BETRIEB, DEM INHALT, DEM ZUGANG ZU ODER DER NUTZUNG DER WEBSITE ENTSTEHEN, NICHT HAFTBAR SIND. SIE STIMMEN ZU, DASS DIESE HAFTUNGSBESCHRÄNKUNG UMFASSEND IST UND FÜR ALLE SCHÄDEN JEGLICHER ART GILT, EINSCHLIESSLICH DIREKTER, INDIREKTER, KOMPENSATIVER, SONDER-, NEBEN-, STRAF- UND FOLGESCHÄDEN, ABER NICHT BESCHRÄNKTER SCHÄDEN ANG NUTZUNG, DATEN ODER ANDERE IMMATERIELLE VERLUSTE (AUCH WENN EIN GRÜNER PLATZ AUF DIE MÖGLICHKEIT SOLCHER SCHÄDEN GEWIESEN WURDE).IN KEINEM FALL STEHT DIE ZUSAMMENGEFASSTE HAFTUNG VON GREEN PLANK (VERTRAG, GARANTIE, HAFTUNG (EINSCHLIESSLICH NACHLÄSSIGKEIT), PRODUKTHAFTUNG, STRENGE HAFTUNG ODER ANDERE THEORIE) AB EINEM NUTZUNGSVERGLEICH VON MEHR ALS 100 EURO ODER IM ZUSAMMENHANG MIT DER NUTZUNG DER NUTZUNG IHR BEZAHLTES GRÜNES BRETT, WENIGER.Bestimmte Gesetze verbieten die Beschränkung stillschweigender Garantien oder den Ausschluss oder die Beschränkung bestimmter Schäden. Wenn diese Gesetze gelten, gelten einige oder alle der oben genannten Ausschlüsse, Ausschlüsse oder Beschränkungen möglicherweise nicht für Sie, und Sie haben möglicherweise zusätzliche Rechte an den hierin enthaltenen Rechten.</p>
                  <h3 className="mb-30 mt-30"><strong>13. </strong>Entschädigung</h3>
                  <p className="mb-30 mt-10">Sie sind verpflichtet, Green Plank und seine leitenden Angestellten, Direktoren, Mitarbeiter, Berater, Vertreter und Vertreter von jeglichem Verlust, jeglicher Haftung, jeglichem Anspruch, jeglichem Klagegrund, jeglicher Forderung, jeglichem Schaden, jeglichen Kosten oder Aufwendungen freizustellen, einschließlich und ohne Einschränkung angemessener rechtlicher, Buchhaltung und andere Honorare, die von Ihnen oder in Ihrem Namen erhoben werden und über die hierin beschriebene Haftung oder von Dritten hinausgehen, und die sich aus oder in Verbindung mit Ihrer Nutzung oder einer Nutzung dieser Website durch autorisierte Benutzer ergeben, einschließlich, aber nicht beschränkt auf Verstöße von Sie oder ein autorisierter Benutzer der Nutzungsbedingungen. Green Plank behält sich das Recht vor, die ausschließliche Verteidigung und Kontrolle von Angelegenheiten zu übernehmen, die von Ihnen entschädigt werden, ohne Ihre Entschädigungsverpflichtungen zu entschuldigen.</p>
                  <h3 className="mb-30 mt-30"><strong>13. </strong>Entschädigung</h3>
                  <p className="mb-30 mt-10">Sie sind verpflichtet, Green Plank und seine leitenden Angestellten, Direktoren, Mitarbeiter, Berater, Vertreter und Vertreter von jeglichem Verlust, jeglicher Haftung, jeglichem Anspruch, jeglichem Klagegrund, jeglicher Forderung, jeglichem Schaden, jeglichen Kosten oder Aufwendungen freizustellen, einschließlich und ohne Einschränkung angemessener rechtlicher, Buchhaltung und andere Honorare, die von Ihnen oder in Ihrem Namen erhoben werden und über die hierin beschriebene Haftung oder von Dritten hinausgehen, und die sich aus oder in Verbindung mit Ihrer Nutzung oder einer Nutzung dieser Website durch autorisierte Benutzer ergeben, einschließlich, aber nicht beschränkt auf Verstöße von Sie oder ein autorisierter Benutzer der Nutzungsbedingungen. Green Plank behält sich das Recht vor, die ausschließliche Verteidigung und Kontrolle von Angelegenheiten zu übernehmen, die von Ihnen entschädigt werden, ohne Ihre Entschädigungsverpflichtungen zu entschuldigen.</p>
                  <h3 className="mb-30 mt-30"><strong>14. </strong>WERKZEUGE & FUNKTIONEN</h3>
                  <p className="mb-30 mt-10">Alle Tools, Funktionen, Taschenrechner usw. werden nur zur Verfügung gestellt. Alle Ergebnisse sind Schätzungen und sind als solche zu verwenden. Green Plank übernimmt keine Verantwortung oder Verantwortung für Informationen, die aus der Verwendung der auf www.GreenPlank.eu bereitgestellten Tools und Funktionen stammen.</p>
                  <h3 className="mb-30 mt-30"><strong>15. </strong>WO KAUFEN / FINDEN SIE EIN PRO / ERHALTEN SIE EIN ANGEBOT</h3>
                  <p className="mb-30 mt-10">Green Plank garantiert nicht, dass wir in der Lage sind, Ihre Servicebedürfnisse mit einem Serviceprofi abzustimmen, oder dass es Serviceprofis in Ihrer Nähe gibt, die entweder in der Lage oder bereit sind, Ihre Servicebedürfnisse zu erfüllen. Obwohl wir bestimmte Schritte unternehmen, um die Qualifikationen unserer gelisteten Serviceprofis zu prüfen, übernimmt Green Plank keine Garantie oder Zusicherung hinsichtlich der Fähigkeiten oder Zusicherungen eines solchen Serviceprofis oder der Qualität der Arbeit, die er oder sie für Sie ausführen kann, wenn Sie sich dafür entscheiden, diese zu behalten ihre Dienste. Green Plank unterstützt oder empfiehlt die Dienste eines bestimmten Serviceprofis nicht. Es liegt ganz bei Ihnen, einen direkten Vertrag abzuschließen oder anderweitig eine Vereinbarung mit einem Serviceprofi zu treffen, und wir übernehmen keine Garantie oder Gewährleistung für deren Leistung am Arbeitsplatz oder für das Ergebnis oder die Qualität der erbrachten Dienstleistungen. Die Serviceprofis sind weder Angestellte noch Vertreter von Green Plank, noch ist Green Plank ein Vertreter der Serviceprofis. Green Plank erbringt keine der von Ihnen in Ihrer Serviceanfrage angeforderten Dienstleistungen und ist nicht für diese verantwortlich. Ihre Rechte aus Verträgen, die Sie mit Serviceprofis abschließen, richten sich nach den Bestimmungen dieser Verträge und den geltenden Gesetzen von Bund, Ländern, Ländern und Gemeinden. Bei Streitigkeiten mit einem Kundendienstmitarbeiter müssen Sie sich direkt an den Kundendienstmitarbeiter wenden und sich hiermit einverstanden erklären, GREEN PLANK (UND UNSERE BEAMTEN, DIREKTOREN, MITARBEITER, MITARBEITER UND VERTRETER) UND ANDERE PERSONEN, FIRMEN ODER EINSCHLIESSLICH UNSERER GESCHÄFTSPARTNER, ZB EINES PRODUKTHERSTELLERS ODER LIEFERANTEN, DER DIE NÜTZLICHE VERWENDBARKEIT VON GREEN PLANK MATCHING BESCHÄDIGEN KÖNNEN, SOWIE FOLGESCHÄDEN UND NEBENSCHÄDEN, VERDÄCHTIGT UND UNVERSTIMMT ODER NICHT OFFENGELEGT, ENTSTEHEN AUS ODER IN IRGENDEINEM ZUSAMMENHANG MIT SOLCHEN STREITIGKEITEN UND IHREN VERHANDLUNGEN MIT DIENSTLEISTERN.</p>
                  <h3 className="mb-30 mt-30"><strong>16. </strong>LINKS</h3>
                  <p className="mb-30 mt-10">Diese Website kann Links zu anderen Websites enthalten, die nur zu Ihrer Bequemlichkeit bereitgestellt werden, und die Aufnahme eines Links bedeutet nicht, dass Green Plank die verlinkte Website oder die darin enthaltenen Informationen befürwortet, untersucht oder überprüft. Green Plank ist nicht für den Inhalt anderer Websites verantwortlich und gibt keine Zusicherung oder Garantie in Bezug auf andere Websites oder den Inhalt oder das Material auf diesen Websites. Wenn Sie sich für den Zugriff auf andere Websites entscheiden, geschieht dies auf eigenes Risiko.</p>
                  <h3 className="mb-30 mt-30"><strong>17. </strong>BEZIEHUNG</h3>
                  <p className="mb-30 mt-10">Die Beziehung zwischen Green Plank und Ihnen wird die eines unabhängigen Auftragnehmers sein, und weder wir noch einer unserer jeweiligen leitenden Angestellten, Vertreter oder Mitarbeiter werden als Partner, Joint Ventures, Treuhänder, Mitarbeiter oder Vertreter des jeweils anderen gehalten oder ausgelegt Ergebnis dieser Vereinbarung oder Nutzung dieser Website.</p>
                  <h3 className="mb-30 mt-30"><strong>18. </strong>GELTENDES RECHT</h3>
                  <p className="mb-30 mt-10">Diese Vereinbarung und ihre Erfüllung unterliegen dem schwedischen Recht in Bezug auf alle Angelegenheiten, die sich aus oder im Zusammenhang mit der Nutzung dieser Website ergeben, sei es wegen vertraglicher, unerlaubter Handlung oder aus sonstigen Gründen, ungeachtet der Bestimmungen über Kollisionsnormen. Sie und Green Plank sind sich einig, dass alle im Rahmen dieser Vereinbarung möglicherweise auftretenden Klagegründe eingeleitet und vor dem zuständigen Gericht in Schweden, Provinz Skåne, verhandelt werden müssen. Sie und Green Plank erklären sich damit einverstanden, sich der persönlichen und ausschließlichen Zuständigkeit der Gerichte im schwedischen Skåne zu unterwerfen. Das Versäumnis von Green Plank, ein Recht oder eine Bestimmung der Nutzungsbedingungen auszuüben oder durchzusetzen, bedeutet keinen Verzicht auf dieses Recht oder diese Bestimmung. Sollte eine Bestimmung der Nutzungsbedingungen von einem zuständigen Gericht für ungültig befunden werden, sind sich die Parteien dennoch einig, dass sich das Gericht bemühen sollte, die in der Bestimmung und den anderen Bestimmungen der Nutzungsbedingungen enthaltenen Absichten der Parteien umzusetzen Die Nutzungsbedingungen bleiben in vollem Umfang erhalten. Sie erklären sich damit einverstanden, dass Ansprüche oder Klagegründe, die sich aus oder im Zusammenhang mit der Nutzung der Produkte und Dienstleistungen oder den Nutzungsbedingungen ergeben, ungeachtet anderslautender Gesetze oder Gesetze innerhalb eines (1) Monats nach einem solchen Anspruch geltend gemacht werden müssen oder Grund der Aktion entstanden oder für immer gesperrt sein.</p>
                  <h3 className="mb-30 mt-30"><strong>19. </strong>ZUORDNUNG</h3>
                  <p className="mb-30 mt-10">Sie dürfen Ihre Rechte, Pflichten oder Verpflichtungen aus diesem Vertrag nicht abtreten, übermitteln, untervergeben oder delegieren.</p>
                  <h3 className="mb-30 mt-30"><strong>20. </strong>GANZE VEREINBARUNG</h3>
                  <p className="mb-30 mt-10">Diese Nutzungsbedingungen bilden zusammen mit den hierin enthaltenen oder hier genannten die gesamte Vereinbarung zwischen uns in Bezug auf den Gegenstand dieser Vereinbarung und ersetzen alle vorherigen Absprachen oder Vereinbarungen (ob elektronisch, mündlich oder schriftlich) in Bezug auf den Gegenstand und können Sie dürfen nur schriftlich oder durch Bereitstellung solcher Ergänzungen oder Änderungen auf dieser Website geändert oder modifiziert werden.</p>
                </div>
              </Col>
            </Row>
          </Container>
        </section>
        <BrandCarousel />
        <Footer />
      </Layout>
    </>
  );
};

export default Forsaljningsvillkor;
