import React from "react";
import Layout from "../components/layout";
import HeaderTwo from "../components/header/header-two";
import StickyHeader from "../components/header/sticky-header";
import PageHeader from "../components/page-header";
import BrandCarousel from "../components/brand-carousel";
import { Container, Row, Col } from "react-bootstrap";
import Footer from "../components/footer";
import Head from "next/head";

const Verkaufsbedingungen = () => {
  return (
    <>
      <Head>
        <title>Verkaufsbedingungen - GreenPlank.de</title>
           <link rel="canonical" href="/verkaufsbedingungen.js" />
        <meta name="title" content="Verkaufsbedingungen - GreenPlank.de
" />
        <meta name="description" content="Lesen Sie dieses Dokument sorgfältig durch. Sie enthält wichtige Informationen zu Ihren Rechten und Pflichten sowie zu Einschränkungen und Ausschlüssen, die für Sie gelten." />
      </Head>
      <Layout pageTitle="Verkaufsbedingungen">
        <HeaderTwo />
        <PageHeader title="Verkaufsbedingungen" crumbTitle="verkaufsbedingungen" />
        <StickyHeader />
        <section className="about-one pt-120 pb-40">
          <Container>
            <Row style={{ marginBottom: "4em" }}>
              <Col lg={12}>
                <h2>Verkaufsbedingungen</h2>
                <div className="mb-30">
                  <p>BITTE LESEN SIE DIESES DOKUMENT SORGFÄLTIG DURCH. ES ENTHÄLT WICHTIGE INFORMATIONEN ÜBER IHRE RECHTE UND VERPFLICHTUNGEN, SOWIE BESCHRÄNKUNGEN UND AUSSCHLÜSSE, DIE FÜR SIE GELTEN.</p>
                  <p className="mb-30 mt-30">Diese Vereinbarung enthält die Geschäftsbedingungen, die für Kunden beim Kauf von Green Plank AB gelten. (im Folgenden als Green Plank bezeichnet) und die auf der Rechnung genannte Green Plank-Einheit, die Ihnen (Kunden) bei Bestellungen von verkauften Produkten zur Verfügung gestellt wird. Der Kunde erklärt sich damit einverstanden, an diese Vereinbarung gebunden zu sein und diese Vereinbarung zu akzeptieren, sofern diese für den Kauf von Produkten von Green Plank und / oder der Green Plank-Internet-Website gilt. Als Verkaufsbedingung erklärt sich der Kunde damit einverstanden, an diese Geschäftsbedingungen gebunden zu sein und diese zu akzeptieren. Diese Geschäftsbedingungen gelten (i), sofern der Kunde keinen separaten formellen Kaufvertrag mit Green Plank unterzeichnet hat. In diesem Fall gilt der separate Vertrag. oder (ii) es sei denn, es gelten andere Green Plank-Standardbedingungen für die hier oder anderswo angegebene Transaktion. Diese Allgemeinen Geschäftsbedingungen können nach freiem Ermessen von Green Planks jederzeit ohne vorherige schriftliche Ankündigung geändert werden.</p>
                  <p className="mb-30 mt-30">IHRE ANNAHME DIESER GESCHÄFTSBEDINGUNGEN IST IN IHRER ANNAHME DER GESCHÄFTSBEDINGUNGEN UND DER NUTZUNG DIESER WEBSITE ENTHALTEN.</p>
                  <h3 className="mb-30 mt-30"><strong>1. </strong>ANNAHMEBEDINGUNGEN FÜR BESTELLUNGEN</h3>
                  <p className="mb-30 mt-30">Der Erhalt einer elektronischen oder einer anderen Form der Auftragsbestätigung durch den Kunden bedeutet weder eine Annahme der Kundenbestellung durch Green Planks noch eine Bestätigung des Verkaufsangebots von Green Planks. Alle Bestellungen werden in Malmö, Schweden, entgegengenommen. Green Plank behält sich das Recht vor, Kundenbestellungen nach Erhalt der Kundenbestellung jederzeit anzunehmen oder abzulehnen, und zwar aus einem vernünftigen Grund, einschließlich, aber nicht beschränkt auf die Nichtverfügbarkeit von Produkten, die Nichteinhaltung von Zahlungsbedingungen durch den Kunden und / oder Verstöße des Kunden gegen diese Vereinbarung . Wenn der Kaufbetrag überwiesen wurde und Green Plank die Bestellung des Kunden storniert, stellt Green Plank unverzüglich eine Rückerstattung in Höhe des Betrags aus, der für die nicht angenommene oder stornierte Bestellung überwiesen wurde.</p>
                  <h3 className="mb-30 mt-30"><strong>2. </strong>ZAHLUNGSBEDINGUNGEN</h3>
                  <p className="mb-30 mt-30">Die Zahlungsbedingungen liegen im alleinigen Ermessen von Green Planks. Sofern von Green Plank nicht anders vereinbart, muss die Zahlung in einer von Green Plank genehmigten Form eingegangen oder anderweitig genehmigt oder gesichert sein, bevor Green Planks einen Auftrag annimmt. Die Zahlung für die Produkte erfolgt per Kreditkarte, Überweisung, elektronischer Überweisung oder einer anderen von Green Plank vereinbarten Zahlungsmethode. Rechnungen sind fällig und zahlbar zu dem / den angegebenen Zahlungstermin (en) per E-Mail, Fax und / oder mündlicher Bestätigung zwischen Green Plank und dem Kunden. Green Plank kann Teile einer Bestellung separat in Rechnung stellen. Bestellungen sind für Green Plank erst dann verbindlich, wenn sie von Green Plank angenommen wurden (siehe Richtlinien zur Auftragsannahme). Alle Angebote von Green Plank gelten für den auf dem Angebot angegebenen Zeitraum. Green Plank behält sich das Recht vor, Angebote nach Bedarf anzupassen oder zu stornieren.</p>
                  <h3 className="mb-30 mt-30"><strong>3. </strong>VERSAND</h3>
                  <p className="mb-30 mt-10">Der Kunde ist für alle Kosten im Zusammenhang mit dem Versand des Produkts an den vom Kunden angegebenen Ort verantwortlich. Es liegt in der Verantwortung des Kunden, Kontaktinformationen bereitzustellen, die es dem Versender ermöglichen, den Kunden zu kontaktieren, wenn der Versand erfolgt. Die Versandkosten gelten nur für die Standardabholung und -zustellung. Der Kunde ist für das Abladen der Ware vom Spediteur verantwortlich. Zusätzliche Lager- und / oder Versandkosten und andere Lagerkosten können anfallen, wenn der Kunde nicht kontaktiert werden kann oder nicht verfügbar ist, um das Produkt zu erhalten. oder wenn das Produkt auf Kundenwunsch umgeleitet wird. Wenn eine Versandrate aufgrund eines Druckfehlers oder eines Fehlers in den Preisinformationen, die von Green Planks-Lieferanten erhalten wurden, mit einer falschen Rate angegeben wird, hat Green Plank das Recht, Bestellungen abzulehnen, anzupassen oder zu stornieren, unabhängig davon, ob die Bestellung bestätigt wurde oder nicht ob die Zahlung überwiesen wurde oder nicht. Der Kunde ist dafür verantwortlich, die Fracht nach Erhalt der Ware auf Mängel oder Anzeichen von Schäden zu untersuchen. Alle Fracht-, Verlust- und Schadensersatzansprüche müssen innerhalb von sieben (7) Werktagen ab dem Datum der Lieferung bei Green Plank eingereicht werden. (siehe 10. Schadensbegrenzung oder kontaktieren Sie uns unter: .) Green Plank haftet nicht für Verzögerungen oder Fehler bei der Ausführung oder Lieferung oder dem Versand von Materialien oder Waren oder für Schäden, die dem Kunden aufgrund einer solchen Verzögerung oder eines solchen Fehlers entstehen, wenn diese Verzögerung oder ein solcher Fehler direkt oder indirekt durch verursacht wird oder in irgendeiner Weise aus höherer Gewalt, Handlungen öffentlicher Feinde, Unruhen, Handlungen von Regierungsbehörden, Arbeitsschwierigkeiten, Versäumnissen der Lieferanten, Waren zu versenden oder herzustellen, Verzögerungen bei der Sicherung oder Verknappung von Rohstoffen, Zusammenbruch oder Zerstörung entstehen oder damit verbunden sind von Anlagen oder Ausrüstungen oder anderen Gründen oder Ursachen, die außerhalb der Kontrolle von Green Plank liegen, auch wenn sie den hier aufgeführten ähnlich sind oder nicht. Alle Bestellungen gelten als ausgesetzt, solange ein solcher Grund die Ausführung, Lieferung oder den Versand verhindert oder verzögert.</p>
                  <h3 className="mb-30 mt-30"><strong>4. </strong>STEUERN</h3>
                  <p className="mb-30 mt-10">Der Kunde ist für alle mit der Bestellung verbundenen Verkaufs-, Verwendungs-, Verbrauchs-, Mehrwert- und sonstigen Kosten verantwortlich, einschließlich etwaiger Zölle, Abfertigungsgebühren oder sonstiger Bestimmungsgebühren. Gegebenenfalls wird eine gesonderte Gebühr für solche Artikel auf der Rechnung von Green Planks ausgewiesen.</p>
                  <h3 className="mb-30 mt-30"><strong>5. </strong>VERSANDSCHADEN</h3>
                  <p className="mb-30 mt-10">Überprüfen Sie Ihr Paket bei der Ankunft auf Beschädigungen. Wenn Sie Schäden bemerken, müssen Sie diese auf dem Frachtbrief vermerken, wenn Sie das Paket unterschreiben, oder wenn keine Unterschrift erforderlich ist, wenden Sie sich sofort an den Spediteur. Wenn auf dem Frachtbrief keine Schäden vermerkt sind, kann Green Plank nicht für Schäden haftbar gemacht werden. Sobald Sie auf dem Frachtbrief vermerkt sind und feststellen, dass Sie das Produkt nicht verwenden können, Kontakt Green Plank per E-Mail oder Telefon, um das beschädigte Material zu melden. Wenn Sie eine Sendung annehmen und keine Schäden melden, und später feststellen, dass tatsächlich Schäden vorliegen, müssen Sie sich innerhalb von 48 Stunden nach Lieferung an das Transportunternehmen wenden, um dies zu melden. Green Plank kann innerhalb von fünfzehn (15) Werktagen ab dem Zeitpunkt der Lieferung oder des versuchten Versands keine Ansprüche in Ihrem Namen geltend machen.</p>
                  <h3 className="mb-30 mt-30"><strong>6. </strong>STORNIERUNGEN</h3>
                  <p className="mb-30 mt-10">Sie haben das Recht, die Bestellung jederzeit innerhalb von 24 Stunden nach Erhalt der Bestellbestätigung von Green Plank zu stornieren. Du wirst brauchen KontaktGreen Plank so schnell wie möglich per E-Mail oder Telefon. Wenn Ihr Kauf bereits versandt wurde, müssen Sie eine Rücksendung veranlassen und sind für die Versandkosten + 20% Auffüllungsgebühr verantwortlich. Wenn der Kauf nicht versandt wurde, können Sie die Stornierung kostenlos zu Ihrer ursprünglichen Zahlungsmethode vornehmen, ausgenommen Transaktionsgebühren.</p>
                  <p>Bestellungen von Einzel- oder Großhändlern, Sonderbestellungen und Sonderanfertigungen, Farben, Modelle, Größen usw. können nicht storniert werden, sobald sie von Green Plank bestätigt wurden.</p>
                  <h3 className="mb-30 mt-30"><strong>7. </strong>RÜCKGABE</h3>
                  <p className="mb-30 mt-10">Wenn Sie es sich anders überlegen, können Sie ungenutzte oder ungeöffnete Artikel innerhalb von sieben (7) Tagen nach Lieferung gegen Erstattung zurücksenden (Versandgebühren sind leider nicht erstattungsfähig). Artikel müssen in neuem, ungeöffnetem und unbenutztem Zustand zurückgesandt werden und enthalten alle Originalmaterialien, die der Sendung beiliegen. Rücksendungen unterliegen einer 20% igen Rücknahmegebühr. Wenden Sie sich an uns, um eine RMA-Nummer (Return Merchandise Authorization) zu erhalten, wenn Sie eine Rücksendung vornehmen möchten. Für jede Rücksendung ist eine RMA-Nummer erforderlich.</p>
                  <p>
                  Nachdem Ihre Artikel in unserem Lager eingetroffen sind, werden sie überprüft. Wenn der Artikel in neuem, ungeöffnetem und unbenutztem Zustand zurückgesandt wird, erhalten Sie eine Rückerstattung zum ursprünglichen Kaufpreis, zuzüglich Umsatzsteuer, sofern diese bei der ursprünglichen Zahlungsmethode anfällt, abzüglich 20% Wiederauffüllungsgebühr abzüglich Versandkosten innerhalb von vier Wochen nach Versand Ihres Pakets an uns. Wenn die Rücksendung auf unseren Fehler zurückzuführen ist, geben Sie dies bitte auf dem Rückversandverpackungsschein an. Wir erstatten Ihnen dann den ursprünglichen Kaufpreis zuzüglich Umsatzsteuer zuzüglich Versandkosten in der ursprünglichen Zahlungsmethode.</p>
                  <h3 className="mb-30 mt-30"><strong>8. </strong>ABLEHNUNGEN</h3>
                  <p className="mb-30 mt-10">Wenn das Paket zum Zeitpunkt der Ankunft abgelehnt wird, sind Sie für die Zustell- und Rücksendekosten + 20% Auffüllungsgebühr verantwortlich. Etwaige Schäden aus verweigerten Lieferungen sind nicht erstattungsfähig und werden nicht zur Kenntnis genommen, da sie verweigert wurden. Wir sind nicht verantwortlich für die mit einer verweigerten Lieferung verbundenen Kosten.</p>
                  <h3 className="mb-30 mt-30"><strong>9. </strong> GARANTIEN</h3>
                  <p className="mb-30 mt-10">Alle angegebenen Garantien sind nur hersteller- / produktspezifische Garantien. Green Plank gewährt keine ausdrücklichen Garantien mit Ausnahme der in dieser Vereinbarung und in der gültigen Garantieerklärung von Green Plank zum Zeitpunkt der Rechnungsstellung angegebenen. Solche Garantien werden wirksam, und Green Plank ist verpflichtet, solche Garantien erst dann zu erfüllen, wenn Green Planks die vollständige Zahlung für den zu garantierenden Artikel erhalten hat. Vor der Rücksendung eines Artikels muss sich der Kunde an die Schadensabteilung von Green Planks wenden. für eine Garantieautorisierungsnummer (WA) innerhalb des vom Hersteller des Produkts angegebenen zulässigen Zeitraums (siehe produktspezifische Garantie). Die WA-Nummer gilt nur für das dort beschriebene Produkt. Das zurückgegebene Produkt muss mit dem zur Rückgabe berechtigten Produkt übereinstimmen. Der Kunde muss sicherstellen, dass alle Rücksendungen innerhalb von dreißig (30) Tagen nach Erhalt der WA-Nummer beim Hersteller / Lieferanten eingehen. Alle Versandvereinbarungen für Rücksendungen oder Umtausch müssen über die Logistikabteilung von Green Planks abgewickelt werden. Der Kunde ist für alle Versand- und Bearbeitungsgebühren für Garantierückgaben verantwortlich, es sei denn, der Hersteller des Produkts hat zugestimmt, diese Kosten zu tragen, oder wie in der Produktgarantie angegeben. Wann immer möglich oder wie unter Garantie beschrieben, müssen alle Artikel in neuwertigem Zustand sein, in der Originalverpackung und mit allen Garantiekarten, Handbüchern und Zubehör. Der Originalverpackungsschein muss beigefügt sein und die WA-Nummer muss auf der Verpackung angegeben sein. Green Plank erfordert möglicherweise eine kurze schriftliche Erklärung und ein Foto oder ein digitales Bild des fehlerhaften Produkts. In einigen Fällen ist eine Inspektion des Produkts vor Ort erforderlich. Die Schadensabteilung von Green Planks wird den Kunden über die Einzelheiten des Garantieanspruchs informieren.</p>
                  <h3 className="mb-30 mt-30"><strong>10. </strong>HAFTUNGSAUSSCHLUSS</h3>
                  <p className="mb-30 mt-10">DIE IN DIESER VEREINBARUNG GENANNTEN GARANTIEN SIND HERSTELLER- / PRODUKTSPEZIFISCHE GARANTIEN FÜR DIE PRODUKTE. GREEN PLANK HAFTET AUSDRÜCKLICH VON ALLEN ANDEREN GARANTIEN, GARANTIEN ODER ZUSICHERUNGEN AB, OB AUSDRÜCKLICH, STILLSCHWEIGEND ODER GESETZLICH, EINSCHLIESSLICH EINER STILLSCHWEIGENDEN GARANTIE DER MARKTGÄNGIGKEIT ODER EIGNUNG FÜR EINEN BESTIMMTEN ZWECK. GREEN PLANK SCHLIESST AUCH JEGLICHE STILLSCHWEIGENDE GARANTIE AUS, DIE AUS DER HANDELSVERWENDUNG ODER AUS EINEM HANDELSVERLAUF ODER EINEM LEISTUNGSVERLAUF ENTSTEHT. GREEN PLANK GARANTIERT NICHT, DASS DIE PRODUKTE FEHLERFREI SIND, ODER GARANTIERT, DASS JEDER FEHLER BEHEBT WIRD. GREEN PLANK GARANTIERT NICHT, DASS ALLE PRODUKTE SPEZIFISCHEN GEOGRAPHISCHEN EINHALTUNGEN ODER VORSCHRIFTEN ENTSPRECHEN. ES IST DIE VERANTWORTUNG DES KUNDEN, ZU GEWÄHRLEISTEN, DASS DIE VERWENDUNG DER GEKAUFTEN PRODUKTE DEN GEMEINSAMEN ZUSTÄNDIGKEITSKODES UND ALLEN REGIONALEN, NATIONALEN UND INTERNATIONALEN GESETZEN UND VORSCHRIFTEN ENTSPRICHT. GREEN PLANK SCHLIESST WEITERHIN PATENT- / GEISTIGE EIGENTUMSRECHTE, GEWÄHRLEISTUNGEN ODER GEWÄHRLEISTUNGEN IN BEZUG AUF VERRIEGELUNGS- / VERBINDUNGSSYSTEME AUS, DIE VON HERSTELLERN VON LAMINAT, ENGINEERED WOOD ODER ANDEREN PRODUKTEN VERKAUFTET WERDEN.</p>
                  <h3 className="mb-30 mt-30"><strong>11. </strong> BESCHRÄNKUNG DER SCHÄDEN</h3>
                  <p className="mb-30 mt-10">GREEN PLANK ÜBERNIMMT KEINE HAFTUNG ÜBER DIE HIERIN FESTGELEGTEN RECHTSMITTEL HINAUS. GREEN PLANK HAFTET NICHT FÜR VERLUST VON GEWINNEN, EINNAHMEN ODER GESCHÄFTSVERLUST ODER ANDEREN FOLGESCHÄDEN, SONDERFÄLLEN, INDIREKTEN ODER STRAFSCHÄDEN, AUCH WENN SIE VORHERSEHEN WURDEN ODER GRÜNES PLANK ÜBER DAS MÖGLICHE SCHÄDEN VERRICHT WURDE VON DRITTEN, MIT AUSNAHME DER AUSDRÜCKLICHEN VORSCHRIFTEN. Der Kunde ist damit einverstanden, dass GREEN PLANK für jegliche Haftung im Zusammenhang mit dem Kauf von Produkten oder Dienstleistungen für Schäden, die über den Gesamtbetrag hinausgehen, der vom Kunden im Rahmen dieser Vereinbarung für den (die) Kaufbetrag (e) gezahlt wurde (n), weder haftbar noch haftbar ist. DIESE EINSCHRÄNKUNG GILT UNABHÄNGIG VON DER FORM DER MASSNAHMEN (ZB WENN DER RECHTSSTREITIGKEITSSTREITIGKEITSSTREITIGKEITSSTREITIGKEITSSTREITIGKEITSSTREITIGKEITSSTREITIGKEITSSTREITIGKEIT).</p>
                  <h3 className="mb-30 mt-30"><strong>12. </strong>GELTENDES RECHT</h3>
                  <p className="mb-30 mt-10">Diese Vereinbarung und ihre Erfüllung unterliegen dem schwedischen Recht in Bezug auf alle Angelegenheiten, die sich aus oder im Zusammenhang mit der Nutzung dieser Website ergeben, sei es wegen vertraglicher, unerlaubter Handlung oder aus sonstigen Gründen, ungeachtet der Bestimmungen über Kollisionsnormen. Sie und Green Plank sind sich einig, dass alle im Rahmen dieser Vereinbarung möglicherweise auftretenden Klagegründe eingeleitet und vor dem zuständigen Gericht in Schweden, Provinz Skåne, verhandelt werden müssen. Sie und Green Plank erklären sich damit einverstanden, sich der persönlichen und ausschließlichen Zuständigkeit der Gerichte im schwedischen Skåne zu unterwerfen. Das Versäumnis von Green Plank, ein Recht oder eine Bestimmung der Nutzungsbedingungen auszuüben oder durchzusetzen, bedeutet keinen Verzicht auf dieses Recht oder diese Bestimmung. Sollte eine Bestimmung der Nutzungsbedingungen durch ein zuständiges Gericht für ungültig befunden werden, vereinbaren die Parteien dennoch, dass das Gericht sich bemühen sollte, die in der Bestimmung und den anderen Bestimmungen der Nutzungsbedingungen enthaltenen Absichten der Parteien umzusetzen Gebrauch bleibt in voller Kraft und Wirkung. Sie erklären sich damit einverstanden, dass Ansprüche oder Klagegründe, die sich aus oder im Zusammenhang mit der Nutzung der Produkte und Dienstleistungen oder den Nutzungsbedingungen ergeben, ungeachtet anderslautender Gesetze oder Gesetze innerhalb eines (1) Monats nach einem solchen Anspruch geltend gemacht werden müssen oder Grund der Aktion entstanden oder für immer gesperrt sein.</p>
                  <h3 className="mb-30 mt-30"><strong>13. </strong>SONSTIGE UNTERLAGEN</h3>
                  <p className="mb-30 mt-10">Anders als in einem gesonderten förmlichen Kaufvertrag zwischen dem Kunden und Green Plank ausdrücklich vorgesehen, dürfen diese Geschäftsbedingungen durch die Verwendung anderer Dokumente NICHT geändert, ergänzt oder ergänzt werden. Jeder Versuch, dieses Dokument zu ändern, zu ergänzen oder zu ergänzen oder eine Bestellung für Produkte zu erfassen, die zusätzlichen oder geänderten Geschäftsbedingungen unterliegen, ist nichtig, sofern in einer schriftlichen Vereinbarung zwischen dem Kunden und Green nichts anderes vereinbart wurde Brett.</p>
                  <h3 className="mb-30 mt-30"><strong>14. </strong>NUTZUNGSBEDINGUNGEN</h3>
                  <p className="mb-30 mt-10">Ihr Zugang zu und Ihre Nutzung der Website werden von Green Planks geregelt Nutzungsbedingungen. Durch die Nutzung dieser Website erklären Sie Ihr Einverständnis, ohne diese Nutzungsbedingungen zu ändern. Die Nutzungsbedingungen können nach freiem Ermessen von Green Planks jederzeit ohne vorherige Ankündigung geändert werden. Daher sollten Sie die Nutzungsbedingungen und die geltenden Richtlinien von Zeit zu Zeit regelmäßig durchlesen, um die für Ihre Nutzung der Website geltenden Bestimmungen und Bedingungen zu verstehen . Im Falle von Widersprüchen zwischen dieser Vereinbarung und den Nutzungsbedingungen haben die Bestimmungen dieser Vereinbarung Vorrang.</p>
                </div>
              </Col>
            </Row>
          </Container>
        </section>
        <BrandCarousel />
        <Footer />
      </Layout>
    </>
  );
};

export default Verkaufsbedingungen;
